import Head from "next/head";
import { Box } from "@chakra-ui/react";
import DataTable from "Shared/components/DataTable";

interface ParcelRow {
  name: string;
  parcel: string;
}

export default function Home() {
  const columns = [
    {
      label: "Nombre",
      selector: (row: ParcelRow) => row.name,
    },
    {
      label: "Parcela",
      selector: (row: ParcelRow) => row.parcel,
    },
  ];
  return (
    <>
      <Head>
        <title>Home</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Box as="main" p={4}>
        <DataTable
          columns={columns}
          data={[
            { name: "Carlos", parcel: "12" },
            { name: "Carlos", parcel: "12" },
            { name: "Carlos", parcel: "12" },
            { name: "Carlos", parcel: "12" },
            { name: "Carlos", parcel: "12" },
            { name: "Carlos", parcel: "12" },
            { name: "Carlos", parcel: "12" },
            { name: "Carlos", parcel: "12" },
          ]}
        />
      </Box>
    </>
  );
}
